### ISSUE TITLE
Mongo Encryption

### ISSUE THREAD

**Issue by algomate-jp** [AlgomateInc/CryptoMarket#1]
Is the Price Server encrypted at all?

Common hack hijacking MongoDb.

**Comment by joncinque** [comment]
There's no encryption or authentication for the Price Server right now, so yeah it's totally open to hacks and all that.  Our best bet would be to enable authentication on the db, have the UI access through a read-only user, and have the scripts access through a read-write user.  Eventually, we could also encrypt the transport of data using TLS/SSL, but it shouldn't be necessary since the price server contains public information.

**Comment by algomate-jp** [comment]
Even though it's public information, it's potentially pretty annoying.

https://nakedsecurity.sophos.com/2017/01/11/thousands-of-mongodb-databases-compromised-and-held-to-ransom/

**Comment by joncinque** [comment]
We'll secure it with authentication no matter what, but I don't think we don't need to secure the transport, unless you really want to have it.

**Comment by algomate-jp** [comment]
No need to secure transport.

**Comment by joncinque** [comment]
This was fixed up last week so we'll be safe now -- credentials provided in the Credentials repo.
